# Generated by Django 4.2.7 on 2023-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0004_delete_thongtinbenhnhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinBenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('CCCD', models.CharField(max_length=12, unique=True)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('quoc_tich', models.CharField(max_length=50)),
                ('noi_sinh', models.CharField(max_length=255)),
                ('noi_cu_tru', models.TextField()),
            ],
        ),
    ]
