# Generated by Django 4.2.7 on 2023-11-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtinbenhnhan',
            old_name='ho_ten',
            new_name='ho_ten_1',
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='CCCD',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
