# Generated by Django 4.2.7 on 2023-11-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_ho_ten_thongtinbenhnhan_ho_ten_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtinbenhnhan',
            old_name='ho_ten_1',
            new_name='ho_ten',
        ),
    ]
