# Generated by Django 4.2.7 on 2023-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_ho_ten_1_thongtinbenhnhan_ho_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='gioi_tinh',
            field=models.CharField(max_length=10),
        ),
    ]
