# Generated by Django 4.2.7 on 2023-11-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_thongtinbenhnhan_gioi_tinh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtinbenhnhan',
            old_name='CCCD',
            new_name='soCCCD',
        ),
    ]
