# Generated by Django 4.2.7 on 2023-11-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_rename_cccd_thongtinbenhnhan_socccd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtinbenhnhan',
            old_name='soCCCD',
            new_name='so',
        ),
    ]
