# Generated by Django 4.2.7 on 2023-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_rename_socccd_thongtinbenhnhan_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='so',
            field=models.CharField(max_length=15),
        ),
    ]
