# Generated by Django 4.2.7 on 2023-11-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_thongtinbenhnhan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
