# Generated by Django 4.2.7 on 2023-11-12 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0013_alter_thongtinbenhnhan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtinbenhnhan',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
