# Generated by Django 4.2.7 on 2023-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_thongtinbenhnhan_user_alter_thongtinbenhnhan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongtinbenhnhan',
            name='user',
        ),
    ]
