# Generated by Django 4.2.7 on 2023-11-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0017_remove_thongtinbenhnhan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtinbenhnhan',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
