# Generated by Django 4.2.7 on 2023-11-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_thongtinbenhnhan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtinbenhnhan',
            old_name='user',
            new_name='user_id',
        ),
    ]
