# Generated by Django 4.2.7 on 2023-11-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_rename_user_thongtinbenhnhan_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtinbenhnhan',
            old_name='user_id',
            new_name='user',
        ),
    ]
