# Generated by Django 4.2.7 on 2023-11-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0025_rename_user_id_thongtinbenhnhan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
