# Generated by Django 4.2.7 on 2023-11-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_thongtinbenhnhan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
