# Generated by Django 4.2.7 on 2023-11-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_doctor_patient_service_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
