# Generated by Django 4.2.7 on 2023-11-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_remove_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.thongtinbenhnhan'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
