# Generated by Django 4.2.7 on 2023-11-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_alter_queue_patient_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_number',
            field=models.IntegerField(default=0),
        ),
    ]
