# Generated by Django 4.2.7 on 2023-11-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_queue_queue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.doctor'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues_for_service', to='Home.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Home.doctor'),
        ),
    ]
