# Generated by Django 4.2.7 on 2023-11-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_alter_queue_doctor_alter_queue_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.doctor'),
        ),
    ]
