# Generated by Django 4.2.7 on 2023-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_alter_queue_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='patient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
