# Generated by Django 4.2.7 on 2023-11-16 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0038_alter_service_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='regis_time',
        ),
        migrations.AddField(
            model_name='queue',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
