# Generated by Django 4.2.7 on 2023-11-16 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0039_remove_queue_regis_time_queue_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='regis_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
