# Generated by Django 4.2.7 on 2023-11-16 11:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0040_queue_regis_time'),
    ]

    operations = [
        # Xóa phần thêm lại trường 'id' nếu nó đã tồn tại
        migrations.RemoveField(
            model_name='queue',
            name='id',
        ),
        
        # Đặt lại trường 'queue_number' thành IntegerField
        migrations.AlterField(
            model_name='queue',
            name='queue_number',
            field=models.IntegerField(default=0),
        ),
    ]