# Generated by Django 4.2.7 on 2023-11-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0056_queue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='QueueInfo',
        ),
    ]
