# Generated by Django 4.2.7 on 2023-11-16 13:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0061_queue'),
    ]

    operations = [
        # Xóa đoạn RemoveField
        # migrations.RemoveField(
        #     model_name='queue',
        #     name='id',
        # ),
        # Giữ lại trường 'id' làm AutoField và làm khóa chính
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.AutoField(primary_key=True),
        ),
        # Giữ lại trường 'queue_number' như mặc định
        migrations.AlterField(
            model_name='queue',
            name='queue_number',
            field=models.IntegerField(default=0),
        ),
    ]