# Generated by Django 4.2.7 on 2023-11-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0064_remove_queueinfo_id_alter_queueinfo_queue_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueueInfo',
        ),
    ]
