# Generated by Django 4.2.7 on 2023-11-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0066_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
