# Generated by Django 4.2.7 on 2023-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0068_alter_queue_doctor_alter_queue_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
