# Generated by Django 4.2.7 on 2023-12-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0069_alter_queue_doctor_alter_queue_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.thongtinbenhnhan'),
        ),
    ]
