# Generated by Django 4.2.7 on 2023-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0070_alter_queue_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='patient',
            field=models.CharField(max_length=100),
        ),
    ]
