# Generated by Django 4.2.7 on 2023-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0072_queue_is_examined'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
