# Generated by Django 4.2.7 on 2024-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0074_alter_queue_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongtinbenhnhan',
            name='noi_cu_tru',
        ),
        migrations.AddField(
            model_name='thongtinbenhnhan',
            name='ngay_cap',
            field=models.DateField(blank=True, null=True),
        ),
    ]
