# Generated by Django 4.2.7 on 2024-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0075_remove_thongtinbenhnhan_noi_cu_tru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='ngay_cap',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='ngay_sinh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
