# Generated by Django 4.2.7 on 2024-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0077_alter_thongtinbenhnhan_ngay_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='ngay_cap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='ngay_sinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
