# Generated by Django 4.2.7 on 2024-01-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0080_alter_thongtinbenhnhan_ngay_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='regis_time',
        ),
    ]
