# Generated by Django 4.2.7 on 2024-01-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0081_remove_queue_regis_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='gioi_tinh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='noi_sinh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='quoc_tich',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thongtinbenhnhan',
            name='so',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
