# Generated by Django 4.2.7 on 2024-01-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0083_queue_birth_year_queue_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='birth_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
